version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - data:/bitnami/mongodb


volumes:
  data:
  pets_img: