version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017"
    volumes:
      - data:/bitnami/mongodb

volumes:
  data:
  app: