version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"

  mongodb:
    image: bitnami/mongodb:latest
    hostname: mongodb_buchi
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data:
  app: